import Footer from "@/components/Footer";

const DoNotSell = () => (
  <div className="min-h-screen bg-background">
    <main className="max-w-3xl mx-auto px-8 pt-32 pb-20">
      <h1 className="font-display text-3xl sm:text-4xl text-foreground mb-2">Do Not Sell or Share My Personal Information</h1>
      <p className="font-editorial text-sm text-muted-foreground mb-12">Last updated: March 14, 2026</p>

      <section className="mb-12 rounded-lg border border-border bg-card p-8 shadow-[var(--shadow-soft)]">
        <p className="font-editorial text-lg text-foreground leading-relaxed font-medium">
          Castle Companion, LLC does not sell or share your personal information.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          As defined by the California Consumer Privacy Act ("CCPA") and the California Privacy Rights Act ("CPRA"), Castle Companion, LLC does not "sell" your personal information to third parties for monetary or other valuable consideration. We also do not "share" your personal information for cross-context behavioral advertising purposes.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">Your Right to Opt Out</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          Under the CCPA/CPRA, California residents have the right to opt out of the sale or sharing of their personal information. While Castle Companion does not engage in the sale or sharing of personal information, we respect and honor this right. If our practices change in the future, we will update this page and provide a clear mechanism for you to opt out.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">What We Do With Your Data</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          We use your personal information solely to provide, personalize, and improve the Castle Companion Service. This includes:
        </p>
        <ul className="font-editorial text-sm text-muted-foreground leading-relaxed list-disc pl-6 space-y-1">
          <li>Creating and managing your account.</li>
          <li>Generating personalized itineraries and Active Automation logistics.</li>
          <li>Processing payments through our PCI DSS-compliant payment processor.</li>
          <li>Sending service-related notifications and SMS communications you have opted in to.</li>
          <li>Performing Mini Memory Maker verification via local Vision AI.</li>
        </ul>
        <p className="font-editorial text-sm text-foreground leading-relaxed mt-4 font-medium">
          We do not sell, rent, lease, or trade your personal information to data brokers, advertisers, or any other third party. AI Inference Data generated by our "Skipper" bots and Local Vision State data processed locally on the user's device remain under sovereign control and are never shared with external parties.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">AI &amp; Data Training</h2>
        <p className="font-editorial text-sm text-foreground leading-relaxed font-medium">
          Castle Companion, LLC does not use your personal data to train global or third-party AI models. All AI inference is performed locally on the user's device or via Enterprise-grade API connections to third-party providers (OpenAI/Gemini) governed by no-training agreements. No personal trip data, photos, child-related information, or consumer behavioral data is used as training input for any large language model or generative AI system.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">Service Providers</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          We may disclose your personal information to service providers who perform services on our behalf (e.g., payment processing, cloud hosting, analytics). These disclosures are not considered "sales" or "sharing" under the CCPA/CPRA. All service providers are contractually obligated to use your personal information only for the purposes for which it was disclosed and to maintain its confidentiality.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">Non-Discrimination</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          We will not discriminate against you for exercising your right to opt out of the sale or sharing of your personal information. You will receive the same level of service, quality, and pricing regardless of whether you exercise your CCPA/CPRA rights.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">How to Submit a Request</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          If you have questions about our data practices or wish to exercise any of your privacy rights, you may contact us at:
        </p>
        <div className="font-editorial text-sm text-muted-foreground leading-relaxed">
          <p>Castle Companion, LLC</p>
          <p>3400 Cottage Way, Ste G2 #34293</p>
          <p>Sacramento, CA 95825</p>
          <p className="mt-2">
            <a href="mailto:privacy@castlecompanion.com" className="text-[hsl(var(--lavender))] hover:underline">privacy@castlecompanion.com</a>
          </p>
        </div>
      </section>
    </main>
    <Footer />
  </div>
);

export default DoNotSell;
