import { Link } from "react-router-dom";
import Footer from "@/components/Footer";

const Privacy = () => (
  <div className="min-h-screen bg-background">
    <main className="max-w-3xl mx-auto px-8 pt-32 pb-20">
      <h1 className="font-display text-3xl sm:text-4xl text-foreground mb-2">Privacy Policy</h1>
      <p className="font-editorial text-sm text-muted-foreground mb-12">Last updated: March 1, 2026</p>

      {/* Notice at Collection */}
      <section className="mb-12 rounded-lg border border-border bg-card p-8 shadow-[var(--shadow-soft)]">
        <h2 className="font-display text-xl text-foreground mb-4">Notice at Collection (CPRA / AB 2013)</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed mb-4">
          Pursuant to the California Consumer Privacy Act (CCPA), the California Privacy Rights Act (CPRA), and California AB 2013, Castle Companion, LLC provides this Notice at Collection to inform California residents of the categories of personal information we collect and the purposes for which it is used.
        </p>
        <ul className="font-editorial text-sm text-muted-foreground leading-relaxed list-disc pl-6 space-y-2">
          <li><strong className="text-foreground">Identifiers:</strong> Name, email address, mobile phone number, unique device identifiers, IP address.</li>
          <li><strong className="text-foreground">Commercial Information:</strong> Records of plans purchased, transaction history, payment method metadata (stored by our PCI-compliant processor).</li>
          <li><strong className="text-foreground">Internet/Electronic Activity:</strong> Browsing history within the Service, feature usage, session data, and interaction with notifications.</li>
          <li><strong className="text-foreground">Geolocation Data:</strong> Precise location data collected with your permission for real-time in-park guidance.</li>
          <li><strong className="text-foreground">Profile &amp; Group Data:</strong> Guest names, ages, ride preferences, dietary restrictions, accessibility needs, and other planning survey responses.</li>
          <li><strong className="text-foreground">AI Inference Data:</strong> Inferences drawn from the above categories to create a profile reflecting your family's preferences, travel patterns, and optimized itinerary strategies. Generated by our "Quiet Companion" RAG system using third-party models (OpenAI/Gemini) for real-time inference. Not shared with third-party data brokers.</li>
          <li><strong className="text-foreground">Local Vision State:</strong> Transient image data processed via local Vision AI on the user's device. This processing does not constitute biometric data collection. No facial geometry, biometric templates, or biometric identifiers are extracted, stored, or transmitted.</li>
        </ul>
        <p className="font-editorial text-sm text-foreground leading-relaxed mt-4 font-medium">
          Castle Companion, LLC does not use your personal data to train global or third-party AI models. Your data is used for immediate inference only and remains sovereign.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">1. Introduction</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          Castle Companion, LLC ("Company," "we," "us," or "our") respects your privacy and is committed to protecting your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our mobile application, website, and related services (collectively, the "Service").
        </p>
        <p className="font-editorial text-sm text-foreground leading-relaxed font-medium">
          Non-Affiliation Disclaimer: Castle Companion, LLC is an independent company and is <strong>not</strong> affiliated with, endorsed by, or associated with The Walt Disney Company, Walt Disney World Resort, Disneyland Resort, Disney Enterprises, Inc., Universal Destinations &amp; Experiences, SeaWorld Parks &amp; Entertainment, or any other theme park owner or operator.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">2. Information We Collect</h2>
        <h3 className="font-display text-base text-foreground mt-6">2.1 Information You Provide</h3>
        <ul className="font-editorial text-sm text-muted-foreground leading-relaxed list-disc pl-6 space-y-2">
          <li><strong className="text-foreground">Account Information:</strong> Name, email address, and password when you create an account.</li>
          <li><strong className="text-foreground">Profile &amp; Group Data:</strong> Guest names, ages, ride preferences, dietary restrictions, accessibility needs (e.g., DAS eligibility), and other survey responses.</li>
          <li><strong className="text-foreground">Payment &amp; Credit Card Information:</strong> Transmitted directly to and stored by our PCI DSS-compliant third-party payment processor using AES-256 encryption. <strong className="text-foreground">We do not store, log, or retain your full credit card number, CVV, or magnetic stripe data on our servers at any time.</strong></li>
          <li><strong className="text-foreground">Mobile Phone Number:</strong> If you opt in to receive SMS/text notifications.</li>
          <li><strong className="text-foreground">Communications:</strong> Messages, feedback, and support inquiries you send to us.</li>
        </ul>
        <h3 className="font-display text-base text-foreground mt-6">2.2 Information Collected Automatically</h3>
        <ul className="font-editorial text-sm text-muted-foreground leading-relaxed list-disc pl-6 space-y-2">
          <li><strong className="text-foreground">Device Information:</strong> Device type, operating system, unique device identifiers, and mobile network information.</li>
          <li><strong className="text-foreground">Precise Geolocation Data:</strong> With your permission, we collect GPS coordinates for real-time, in-park guidance. Classified as Sensitive Personal Information (SPI) under the CPRA. <strong className="text-foreground">Deleted or anonymized within 24 hours</strong> of the conclusion of your park day.</li>
          <li><strong className="text-foreground">Usage Data:</strong> Pages visited, features used, interactions with notifications, session duration, and app performance metrics.</li>
          <li><strong className="text-foreground">Cookies &amp; Similar Technologies:</strong> We use cookies, pixel tags, and similar technologies on our website.</li>
        </ul>
        <h3 className="font-display text-base text-foreground mt-6">2.3 Information from Third Parties</h3>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          We may receive information from third-party services you connect to your account (e.g., sign-in via Apple or Google), as well as publicly available theme park data.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">3. How We Use Your Information</h2>
        <ul className="font-editorial text-sm text-muted-foreground leading-relaxed list-disc pl-6 space-y-1">
          <li>Create and manage your account.</li>
          <li>Generate personalized itineraries and real-time recommendations.</li>
          <li>Send contextual, in-park notifications.</li>
          <li>Process payments and manage your subscription or plan.</li>
          <li>Provide customer support.</li>
          <li>Improve and optimize the Service through analytics.</li>
          <li>Send marketing communications (only with your consent).</li>
          <li>Detect, prevent, and address fraud, security issues, or technical problems.</li>
          <li>Comply with legal obligations.</li>
        </ul>
      </section>

      {/* SMS section with Twilio compliance clause */}
      <section id="sms" className="mb-12 rounded-lg border border-border bg-card p-8 shadow-[var(--shadow-soft)]">
        <div className="flex items-center gap-3 mb-6">
          <span className="text-lg">📱</span>
          <h2 className="font-display text-xl text-foreground">3A. SMS / Text Message Communications</h2>
        </div>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed mb-4">
          Castle Companion may offer SMS/text message notifications for real-time park alerts, dining reservation confirmations, itinerary updates, and other service-related communications. By opting in, you consent to receive automated and non-automated text messages at the mobile number you provide.
        </p>
        <ul className="font-editorial text-sm text-muted-foreground leading-relaxed list-disc pl-6 space-y-2">
          <li><strong className="text-foreground">Opt-In/Opt-Out:</strong> SMS communications are entirely optional. You may opt out at any time by replying STOP, adjusting your account settings, or contacting <a href="mailto:support@castlecompanion.com" className="text-[hsl(var(--lavender))] hover:underline">support@castlecompanion.com</a>.</li>
          <li><strong className="text-foreground">Message Frequency:</strong> Varies based on your park visit activity. During an active park day, you may receive up to 15 messages.</li>
          <li><strong className="text-foreground">Message &amp; Data Rates:</strong> Standard message and data rates from your wireless carrier may apply.</li>
          <li><strong className="text-foreground">Carriers:</strong> SMS services are supported on major U.S. carriers. Carriers are not liable for delayed or undelivered messages.</li>
          <li><strong className="text-foreground">Data Use:</strong> Your mobile phone number collected for SMS purposes will not be sold, rented, or shared with third parties for their marketing purposes.</li>
          <li><strong className="text-foreground">Help:</strong> Reply HELP to any message or contact <a href="mailto:support@castlecompanion.com" className="text-[hsl(var(--lavender))] hover:underline">support@castlecompanion.com</a>.</li>
        </ul>
        <div className="mt-6 pt-4 border-t border-border">
          <p className="font-editorial text-sm text-foreground leading-relaxed font-medium">
            Mobile information will not be shared with third parties/affiliates for marketing or promotional purposes. All the above categories exclude text messaging originator opt-in data and consent; this information will not be shared with any third parties.
          </p>
        </div>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">4. How We Share Your Information</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">We do not sell your personal information. We may share your information in the following circumstances:</p>
        <ul className="font-editorial text-sm text-muted-foreground leading-relaxed list-disc pl-6 space-y-2">
          <li><strong className="text-foreground">Service Providers:</strong> Trusted third parties who perform services on our behalf (payment processing, cloud hosting, analytics, email delivery).</li>
          <li><strong className="text-foreground">Cloud AI Service Providers:</strong> Our "Quiet Companion" ecosystem transmits limited, anonymized contextual data to third-party AI providers (OpenAI/Gemini) for real-time inference only. Governed by Enterprise-grade API agreements that prohibit use of your data for model training.</li>
          <li><strong className="text-foreground">Legal Requirements:</strong> When required by law, regulation, legal process, or governmental request.</li>
          <li><strong className="text-foreground">Business Transfers:</strong> In connection with a merger, acquisition, or sale of assets.</li>
          <li><strong className="text-foreground">With Your Consent:</strong> When you explicitly authorize us to share information.</li>
        </ul>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">5. Data Retention</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          We retain your personal information for as long as your account is active or as needed to provide the Service. If you delete your account, we will remove your personal data within 30 days, except where retention is required by law. Anonymized and aggregated data may be retained indefinitely for analytics and product improvement.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">6. Data Security</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          We implement industry-standard technical and organizational measures to protect your information, including encryption in transit (TLS/SSL) and at rest, access controls, and regular security audits. However, no method of electronic transmission or storage is 100% secure.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">7. Your Rights &amp; Choices</h2>
        <h3 className="font-display text-base text-foreground mt-6">7.1 All Users</h3>
        <ul className="font-editorial text-sm text-muted-foreground leading-relaxed list-disc pl-6 space-y-1">
          <li><strong className="text-foreground">Access &amp; Update:</strong> You may access and update your account information at any time through the App.</li>
          <li><strong className="text-foreground">Delete Account:</strong> You may request deletion by contacting <a href="mailto:privacy@castlecompanion.com" className="text-[hsl(var(--lavender))] hover:underline">privacy@castlecompanion.com</a>.</li>
          <li><strong className="text-foreground">Location Services:</strong> You may disable location tracking through your device settings.</li>
          <li><strong className="text-foreground">Marketing Opt-Out:</strong> Unsubscribe from marketing emails at any time using the link in each email.</li>
          <li><strong className="text-foreground">Push Notifications:</strong> Manage notification preferences in your device settings or within the App.</li>
        </ul>
        <h3 className="font-display text-base text-foreground mt-6">7.2 California Residents (CCPA/CPRA)</h3>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          If you are a California resident, you have the right to: (a) know what personal information we collect, use, and disclose; (b) request deletion; (c) opt out of the sale or sharing of personal information (we do not sell personal information); and (d) not be discriminated against for exercising your rights. Contact <a href="mailto:privacy@castlecompanion.com" className="text-[hsl(var(--lavender))] hover:underline">privacy@castlecompanion.com</a>. See also our <Link to="/privacy-ca" className="text-[hsl(var(--lavender))] hover:underline">California Privacy Notice</Link>.
        </p>
        <h3 className="font-display text-base text-foreground mt-6">7.3 European Economic Area (GDPR)</h3>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          If you are located in the EEA, you have additional rights including access, rectification, erasure, restriction, objection, portability, and withdrawal of consent. Contact us or your local data protection authority.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">8. Children's Privacy &amp; Local Vision AI</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          The Service is not directed to children under 13. We do not knowingly collect personal information from children under 13. Group planning features allow adults to include children's names and preferences; this information is collected from and controlled by the adult account holder.
        </p>
        <p className="font-editorial text-sm text-foreground leading-relaxed font-medium">
          Minors Under 16 (CPRA): Castle Companion, LLC does not "sell" or "share" (as defined under CCPA/CPRA) the personal information of any user under the age of 16.
        </p>
        <h3 className="font-display text-base text-foreground mt-6">8.1 Mini Memory Maker &amp; Local Processing</h3>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          Photos used for the "Mini Memory Maker" scavenger hunt feature are processed locally on the user's device. These images are <strong className="text-foreground">never uploaded to a persistent cloud database</strong> and are never used for facial recognition training or biometric profiling.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">9. Third-Party Links &amp; Services</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          The Service may contain links to third-party websites or services not operated by us. We are not responsible for the privacy practices of these third parties.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">10. Data Breach Notification</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          In the event of a data breach, we will notify affected users in accordance with applicable federal and state laws, including California Civil Code § 1798.82, as promptly as practicable and without unreasonable delay.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">11. International Data Transfers</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          The Service is operated from the United States. If you access the Service from outside the United States, your information may be transferred to, stored, and processed in the United States. By using the Service, you consent to the transfer of your information to the United States.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">12. Limitation of Liability for Data Practices</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          While we implement commercially reasonable security measures, no method of electronic transmission or data storage is completely secure. Castle Companion, LLC shall not be liable for any unauthorized access resulting from circumstances beyond our reasonable control. You acknowledge the inherent risks of providing information online.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">13. AI Transparency &amp; Model Disclosure (AB 2013)</h2>
        <h3 className="font-display text-base text-foreground mt-6">13.1 Model &amp; Architecture Disclosure</h3>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          Our "Quiet Companion" system utilizes Retrieval-Augmented Generation (RAG) powered by third-party large language models (OpenAI and Gemini). Local Vision AI for Mini Memory Maker runs on the user's device.
        </p>
        <h3 className="font-display text-base text-foreground mt-6">13.2 No-Training Guarantee</h3>
        <p className="font-editorial text-sm text-foreground leading-relaxed font-medium">
          We do not use your personal trip data, "Mini Memory Maker" photos, or interaction history to train or modify our underlying models or those of our third-party providers. All interactions with third-party AI providers are governed by Enterprise-grade API terms that prohibit the use of customer data for model training.
        </p>
        <h3 className="font-display text-base text-foreground mt-6">13.3 Purpose of AI Use</h3>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          AI is used exclusively for: (a) real-time park nudges and recommendations via RAG inference; (b) Active Automation of theme park logistics; and (c) Mini Memory Maker verification via local Vision AI.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">14. Automated Recommendations &amp; Human-in-the-Loop (AB 316)</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          Castle Companion, LLC accepts responsibility for the integrity of its AI outputs. However, all automated nudges and recommendations are advisory. <strong className="text-foreground">Users acknowledge that they are the final human-in-the-loop and maintain full responsibility for their physical safety and compliance with theme park rules.</strong>
        </p>
        <h3 className="font-display text-base text-foreground mt-6">14.2 AI Interaction Notice</h3>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          During active park days, users will receive a recurring disclosure notice every 3 hours identifying the system as an artificial intelligence. This notice cannot be disabled as it is required for regulatory compliance.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">15. Pricing Transparency (SB 53)</h2>
        <h3 className="font-display text-base text-foreground mt-6">15.1 Direct-to-Sovereign Discount</h3>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          Prices for plans purchased through the Castle Companion web application are $10–$20 lower than those offered through third-party mobile application storefronts. This pricing differential reflects the reduced administrative costs and elimination of third-party distribution fees. <strong className="text-foreground">This discount is not a financial incentive for the sale, sharing, or disclosure of personal information.</strong>
        </p>
        <h3 className="font-display text-base text-foreground mt-6">15.2 Non-Discrimination</h3>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          Users who purchase through the higher-priced App Store channel receive the same privacy protections, service quality, features, and data rights as web purchasers.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">16. Changes to This Policy</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          We may update this Privacy Policy from time to time. The most current version will always be available within the App and on our website. If we make material changes, we will notify you through the Service or via email prior to the changes taking effect.
        </p>
      </section>

      <section className="mb-12 space-y-4">
        <h2 className="font-display text-xl text-foreground">17. Contact Us</h2>
        <p className="font-editorial text-sm text-muted-foreground leading-relaxed">
          If you have any questions, concerns, or requests regarding this Privacy Policy, please contact us:
        </p>
        <div className="font-editorial text-sm text-muted-foreground leading-relaxed">
          <p>Castle Companion, LLC</p>
          <p>3400 Cottage Way, Ste G2 #34293</p>
          <p>Sacramento, CA 95825</p>
          <p className="mt-2">
            <a href="mailto:privacy@castlecompanion.com" className="text-[hsl(var(--lavender))] hover:underline">privacy@castlecompanion.com</a>
          </p>
        </div>
      </section>
    </main>
    <Footer />
  </div>
);

export default Privacy;
